log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k3s0
      # renovate: datasource=github-tags depName=k3s-io/k3s versioning=regex:^v(?<major>1)\.(?<minor>31)\.(?<patch>\d+)\+k3s(?<build>\d+)$
      k3s_version: v1.31.14+k3s1
      k3s_sha_amd: 4e4ff40e0867d9e5a21164c4497094ab341b96fd1f1c09010974a894faa387b7
      k3s_sha_arm: 0c38b17d04f2ff9b3878799c360f65e40fbb7c7d3840167a4e6d8c180753f86a
      # renovate: datasource=github-releases depName=alexellis/k3sup versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k3sup_version: 0.13.11
      k3sup_sha_amd: 46ee77da750ad2d2961c48848883f1b017444c0fc4dea44d3f47feefcce090a2
      k3sup_sha_arm: 6bcb7e72d35ce33fe1d877965622537606cf52941a910e7bb8ec61f87b1ae97f
